name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
      shell: pwsh
        
    - name: Run unit tests
      run: |
        python -m pytest music_streaming/tests/unit/
      shell: pwsh
        
    - name: Generate coverage report
      run: |
        python -m pytest --cov=music_streaming music_streaming/tests/unit/ --cov-report=xml
      shell: pwsh
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false